# Checks security, runs unit tests, and publishes a composer package
# See https://git.luminfire.net/templates/gitlab/ci-templates/-/tree/master/composer-package
#
# See also:
# - https://docs.gitlab.com/ee/user/packages/
# - https://docs.gitlab.com/13.2/ee/user/packages/composer_repository/index.html
# - https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Composer.gitlab-ci.yml

stages:
  - solcare
  - test
  - build

# Cache files for use between jobs and pipelines.
cache:
  key: $CI_COMMIT_REF_SLUG
  paths:
    - .npm
    - vendor
    - node_modules
    - public

include:
  - project: 'templates/gitlab/ci-templates'
    file:
      - 'generic/merge-request-workflow.yml'
      - 'generic/sast.yml'
      - 'solcare/composer.yml'
      - 'security/lockfiles.yml'
      - 'test/phpunit.yml'
      - 'build/composer-package.yml'
